<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <RootNamespace/>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\EccsLogicWorldAPI\EccsLogicWorldAPI.csproj"/>
        <ProjectReference Include="..\EccsGuiBuilder\EccsGuiBuilder.csproj"/>
    </ItemGroup>
    
    <ItemGroup>
        <Reference Include="0Harmony">
            <HintPath>HarmonyForLogicWorld\HarmonyForLogicWorld\assemblies\client\0Harmony.dll</HintPath>
        </Reference>
        <Reference Include="LogicAPI.Client">
            <HintPath>$(LogicWorldGameLocation)\Logic_World_Data\Managed\LogicAPI.Client.dll</HintPath>
        </Reference>
        <Reference Include="LogicAPI">
            <HintPath>$(LogicWorldGameLocation)\Logic_World_Data\Managed\LogicAPI.dll</HintPath>
        </Reference>
        <Reference Include="LogicAPI.Server">
            <HintPath>$(LogicWorldGameLocation)\Server\LogicAPI.Server.dll</HintPath>
        </Reference>
        <Reference Include="LogicLocalization">
            <HintPath>$(LogicWorldGameLocation)\Logic_World_Data\Managed\LogicLocalization.dll</HintPath>
        </Reference>
        <Reference Include="LogicLog">
            <HintPath>$(LogicWorldGameLocation)\Logic_World_Data\Managed\LogicLog.dll</HintPath>
        </Reference>
        <Reference Include="LogicUI">
            <HintPath>$(LogicWorldGameLocation)\Logic_World_Data\Managed\LogicUI.dll</HintPath>
        </Reference>
        <Reference Include="LogicWorld.Building">
            <HintPath>$(LogicWorldGameLocation)\Logic_World_Data\Managed\LogicWorld.Building.dll</HintPath>
        </Reference>
        <Reference Include="LogicWorld.BuildingManagement">
            <HintPath>$(LogicWorldGameLocation)\Logic_World_Data\Managed\LogicWorld.BuildingManagement.dll</HintPath>
        </Reference>
        <Reference Include="LogicWorld.ClientCode">
            <HintPath>$(LogicWorldGameLocation)\Logic_World_Data\Managed\LogicWorld.ClientCode.dll</HintPath>
        </Reference>
        <Reference Include="LogicWorld">
            <HintPath>$(LogicWorldGameLocation)\Logic_World_Data\Managed\LogicWorld.dll</HintPath>
        </Reference>
        <Reference Include="JimmysUnityUtilities">
            <HintPath>$(LogicWorldGameLocation)\Logic_World_Data\Managed\JimmysUnityUtilities.dll</HintPath>
        </Reference>
        <Reference Include="LogicWorld.Interfaces">
            <HintPath>$(LogicWorldGameLocation)\Logic_World_Data\Managed\LogicWorld.Interfaces.dll</HintPath>
        </Reference>
        <Reference Include="LogicWorld.Rendering">
            <HintPath>$(LogicWorldGameLocation)\Logic_World_Data\Managed\LogicWorld.Rendering.dll</HintPath>
        </Reference>
        <Reference Include="LogicWorld.SharedCode">
            <HintPath>$(LogicWorldGameLocation)\Logic_World_Data\Managed\LogicWorld.SharedCode.dll</HintPath>
        </Reference>
        <Reference Include="LogicWorld.UI">
            <HintPath>$(LogicWorldGameLocation)\Logic_World_Data\Managed\LogicWorld.UI.dll</HintPath>
        </Reference>
        <Reference Include="MessagePack.Annotations">
            <HintPath>$(LogicWorldGameLocation)\Server\MessagePack.Annotations.dll</HintPath>
        </Reference>
        <Reference Include="MessagePack">
            <HintPath>$(LogicWorldGameLocation)\Server\MessagePack.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine">
            <HintPath>$(LogicWorldGameLocation)\Logic_World_Data\Managed\UnityEngine.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>$(LogicWorldGameLocation)\Logic_World_Data\Managed\UnityEngine.UI.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(LogicWorldGameLocation)\Logic_World_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="TMPro">
            <HintPath>$(LogicWorldGameLocation)\Logic_World_Data\Managed\Unity.TextMeshPro.dll</HintPath>
        </Reference>
        <Reference Include="LICC">
            <HintPath>$(LogicWorldGameLocation)\Server\LICC.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>